version: "3.2"

networks:
  default:
    external:
      name: calc-net

services:
  zookeeper:
    image: zookeeper
    restart: always

  vertx_sd:
    image: srinskit/vertx_sd
    restart: always
    volumes:
      - type: bind
        source: /tmp/metrics-targets
        target: /tmp/metrics-targets
    depends_on:
      - zookeeper

  prometheus:
    image: srinskit/prometheus
    restart: always
    ports:
      - "9090:9090"
    user: root
    volumes:
      - type: volume
        source: prometheus-volume
        target: /prometheus
        volume:
          nocopy: true
      - type: bind
        source: /tmp/metrics-targets
        target: /tmp/metrics-targets
        read_only: true
    depends_on:
      - zookeeper

  grafana:
    image: srinskit/grafana
    restart: always
    user: root
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: grafana-volume
        target: /var/lib/grafana
        volume:
          nocopy: true
    depends_on:
      - prometheus

volumes:
  prometheus-volume:
  grafana-volume:
