version: "3.2"

networks:
  default:
    external:
      name: calc-net

services:
  zookeeper:
    image: zookeeper
    restart: always

  vertx_sd:
    image: srinskit/vertx_sd
    restart: always
    volumes:
      - type: bind
        source: /tmp/metrics-targets
        target: /tmp/metrics-targets
    depends_on:
      - zookeeper
      
  prometheus:
    image: srinskit/prometheus
    restart: always
    user: root
    ports:
      - "9090:9090"
    volumes:
      - type: volume
        source: prometheus-volume
        target: /prometheus
        volume:
          nocopy: true
      - type: bind
        source: /tmp/metrics-targets
        target: /tmp/metrics-targets
        read_only: true
    depends_on:
      - zookeeper

  grafana:
    image: srinskit/grafana
    restart: always
    ports:
      - "3000:3000"
    user: root
    volumes:
      - type: volume
        source: grafana-volume
        target: /data/grafana
        volume:
          nocopy: true
    depends_on:
      - prometheus

  adder:
    image: srinskit/calc-adder-service
    depends_on:
      - zookeeper

  divider:
    image: srinskit/calc-divider-service
    depends_on:
      - zookeeper

  api-server:
    image: srinskit/calc-api-server
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: calc-volume
        target: /data
        volume:
          nocopy: true
    depends_on:
      - zookeeper

volumes:
  calc-volume:
  prometheus-volume:
  grafana-volume:
