{
 "title": "Vertx-Prom -2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Quick facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Current  CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 2, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{ instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{instance=\"$instance\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{instance=\"$instance\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{instance=\"$instance\"}",
       "legendFormat": "system-1m"
      },
      {
       "expr": "system_cpu_count{instance=\"$instance\"}",
       "legendFormat": "cpus"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"$instance\"}",
       "legendFormat": "peak"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Service requests by Instance and service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Service_requestCount_total[1m])) by (instance,service)"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vertx_http_server_connections", "legendFormat": "{{local}}" }
   ]
  },
  {
   "title": "Request count rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total[1m])) by (code), 0.001)"
    }
   ]
  },
  {
   "title": "Request count rate by code and path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total[1m])) by (code,path), 0.001)"
    }
   ]
  },
  {
   "title": "Global response time/latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum[1m])) / sum(irate(vertx_http_server_responseTime_seconds_count[1m]))",
     "legendFormat": "1 minute  instant latency"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    },
    {
     "expr": "sum(rate(vertx_http_server_responseTime_seconds_sum[1m])) / sum(rate(vertx_http_server_responseTime_seconds_count[1m]))",
     "legendFormat": "1 minute latency "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vertx_http_server_responseTime_seconds_count{path=\"/add/:x/:y/\",code=\"200\"}[1m])/rate(vertx_http_server_responseTime_seconds_sum{path=\"/add/:x/:y/\",code=\"200\"}[1m])"
    }
   ]
  },
  {
   "title": "Response time by path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum[1m])) by (path) / sum(irate(vertx_http_server_responseTime_seconds_count[1m])) by (path)",
     "legendFormat": "{{path}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,path))",
     "legendFormat": "{{path}} [med]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,path))",
     "legendFormat": "{{path}} [99p]"
    }
   ]
  },
  {
   "title": "Total HTTP Server bytes sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesSent_sum[1m])) / sum(rate(vertx_http_server_bytesSent_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Total  HTTP Server bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesReceived_sum[1m])) / sum(rate(vertx_http_server_bytesReceived_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  { "title": "Event Bus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vertx_eventbus_handlers", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vertx_eventbus_pending", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Eventbus: total sent rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_sent_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: total received rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus : processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Eventbus: processing time by address",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) by (address) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m])) by (address)",
     "legendFormat": "{{address}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address))",
     "legendFormat": "{{address}} [med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address))",
     "legendFormat": "{{address}} [95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address))",
     "legendFormat": "{{address}} [99p]"
    }
   ]
  }
 ]
}